import type { PrismaClient } from '@prisma/client'

type ServicoSeed = {
  codigo: string
  nome: string
  descricao: string
  categoria: string
  subcategoria?: string
  horasTecnicasBase: number
  fatorComplexidade: number
  valorReferenciaHora: number
  obrigacaoBaseCodigo?: string
  fonte: 'enviro-clarity-main' | 'posto-extension'
  codigoOrigem?: string
  demandType?: string
  sphere?: string
  agencies?: string[]
  complexity?: 'Baixa' | 'Média' | 'Alta'
  professionals?: string[]
  deliverableType?: string
  precoBase?: number
  precoMin?: number
  precoMax?: number
  custoInterno?: number
  margem?: number
  fluxo?: 'pontual' | 'continuo'
  requerDiagnostico?: boolean
  orcamentoDireto?: boolean
}

const SERVICOS: ServicoSeed[] = [
  {
    codigo: 'PST-AMB-001',
    nome: 'Diagnóstico e estratégia de licenciamento para posto',
    descricao: 'Estruturação técnica do caminho regulatório para licença de operação, renovação ou regularização ambiental do posto.',
    categoria: 'Licenciamento Ambiental',
    subcategoria: 'Regularização e Gestão',
    horasTecnicasBase: 24,
    fatorComplexidade: 1.1,
    valorReferenciaHora: 200,
    obrigacaoBaseCodigo: 'AMB-001',
    fonte: 'posto-extension',
    demandType: 'Diagnóstico / Regularização',
    sphere: 'Estadual / Municipal',
    agencies: ['Órgão ambiental estadual', 'Prefeitura'],
    complexity: 'Média',
    professionals: ['Engenheiro ambiental', 'Analista regulatório'],
    deliverableType: 'Relatório técnico e plano de ação',
    precoBase: 5200,
    precoMin: 3200,
    precoMax: 9600,
    custoInterno: 2200,
    margem: 58,
    fluxo: 'pontual',
    requerDiagnostico: true,
    orcamentoDireto: false,
  },
  {
    codigo: 'LIC-011',
    nome: 'Plano de Gerenciamento de Resíduos Sólidos (PGRS/PGRCC)',
    descricao: 'Gestão de resíduos sólidos ambientais com identificação, segregação, armazenamento, transporte e destinação final adequada.',
    categoria: 'Estudos Ambientais e Passivo',
    subcategoria: 'Gestão de Resíduos',
    horasTecnicasBase: 32,
    fatorComplexidade: 1,
    valorReferenciaHora: 180,
    obrigacaoBaseCodigo: 'AMB-002',
    fonte: 'enviro-clarity-main',
    codigoOrigem: 'EST-012',
    demandType: 'Condicionante / Novo licenciamento',
    sphere: 'Estadual / Federal',
    agencies: ['SEMAD-GO', 'Prefeitura', 'IBAMA'],
    complexity: 'Baixa',
    professionals: ['Engenheiro ambiental', 'Sanitarista'],
    deliverableType: 'Plano técnico',
    precoBase: 4000,
    precoMin: 2500,
    precoMax: 8000,
    custoInterno: 1800,
    margem: 55,
    fluxo: 'pontual',
    requerDiagnostico: true,
    orcamentoDireto: true,
  },
  {
    codigo: 'PST-AMB-003',
    nome: 'Plano de Atendimento a Emergências (PAE) para posto',
    descricao: 'Elaboração e revisão do PAE com cenários de vazamento, incêndio, contaminação e resposta operacional para postos de combustíveis.',
    categoria: 'Licenciamento Ambiental',
    subcategoria: 'Planos operacionais',
    horasTecnicasBase: 20,
    fatorComplexidade: 1,
    valorReferenciaHora: 190,
    obrigacaoBaseCodigo: 'AMB-003',
    fonte: 'posto-extension',
    demandType: 'Plano técnico',
    sphere: 'Estadual / Municipal',
    agencies: ['Órgão ambiental estadual', 'Corpo de Bombeiros'],
    complexity: 'Média',
    professionals: ['Engenheiro ambiental', 'Engenheiro de segurança'],
    deliverableType: 'Plano técnico',
    precoBase: 4200,
    precoMin: 2800,
    precoMax: 7600,
    custoInterno: 1800,
    margem: 57,
    fluxo: 'pontual',
    requerDiagnostico: true,
    orcamentoDireto: true,
  },
  {
    codigo: 'PST-AMB-004',
    nome: 'Laudo de estanqueidade de tanques subterrâneos',
    descricao: 'Coordenação técnica, acompanhamento e consolidação documental do teste de estanqueidade dos tanques do SASC.',
    categoria: 'Monitoramento Ambiental',
    subcategoria: 'SASC e integridade',
    horasTecnicasBase: 12,
    fatorComplexidade: 1,
    valorReferenciaHora: 220,
    obrigacaoBaseCodigo: 'AMB-004',
    fonte: 'posto-extension',
    demandType: 'Laudo técnico',
    sphere: 'Estadual / Municipal',
    agencies: ['Órgão ambiental estadual'],
    complexity: 'Média',
    professionals: ['Engenheiro ambiental', 'Técnico especializado SASC'],
    deliverableType: 'Laudo técnico',
    precoBase: 3600,
    precoMin: 2400,
    precoMax: 6800,
    custoInterno: 1700,
    margem: 53,
    fluxo: 'pontual',
    requerDiagnostico: false,
    orcamentoDireto: true,
  },
  {
    codigo: 'PST-AMB-005',
    nome: 'Laudo de estanqueidade de tubulações e conexões',
    descricao: 'Coordenação técnica e consolidação documental do teste de estanqueidade das linhas, conexões e acessórios do sistema subterrâneo.',
    categoria: 'Monitoramento Ambiental',
    subcategoria: 'SASC e integridade',
    horasTecnicasBase: 12,
    fatorComplexidade: 1,
    valorReferenciaHora: 220,
    obrigacaoBaseCodigo: 'AMB-005',
    fonte: 'posto-extension',
    demandType: 'Laudo técnico',
    sphere: 'Estadual / Municipal',
    agencies: ['Órgão ambiental estadual'],
    complexity: 'Média',
    professionals: ['Engenheiro ambiental', 'Técnico especializado SASC'],
    deliverableType: 'Laudo técnico',
    precoBase: 3400,
    precoMin: 2200,
    precoMax: 6200,
    custoInterno: 1600,
    margem: 53,
    fluxo: 'pontual',
    requerDiagnostico: false,
    orcamentoDireto: true,
  },
  {
    codigo: 'PST-AMB-006',
    nome: 'Investigação de passivo ambiental e plano de resposta',
    descricao: 'Diagnóstico técnico de passivo, interface com laboratório e estruturação de plano de resposta para área suspeita ou contaminada.',
    categoria: 'Estudos Ambientais e Passivo',
    subcategoria: 'Passivo ambiental',
    horasTecnicasBase: 40,
    fatorComplexidade: 1.3,
    valorReferenciaHora: 220,
    obrigacaoBaseCodigo: 'AMB-006',
    fonte: 'posto-extension',
    demandType: 'Diagnóstico / Estudo',
    sphere: 'Estadual / Federal',
    agencies: ['Órgão ambiental estadual'],
    complexity: 'Alta',
    professionals: ['Engenheiro ambiental', 'Geólogo'],
    deliverableType: 'Relatório técnico',
    precoBase: 9800,
    precoMin: 6200,
    precoMax: 18000,
    custoInterno: 4300,
    margem: 56,
    fluxo: 'pontual',
    requerDiagnostico: true,
    orcamentoDireto: false,
  },
  {
    codigo: 'PST-ANP-001',
    nome: 'Regularização e atualização de registro ANP',
    descricao: 'Suporte técnico e documental para abertura, atualização ou revalidação do registro ANP do revendedor varejista.',
    categoria: 'Gestão e Consultoria Ambiental',
    subcategoria: 'Regulação ANP',
    horasTecnicasBase: 10,
    fatorComplexidade: 0.9,
    valorReferenciaHora: 180,
    obrigacaoBaseCodigo: 'ANP-001',
    fonte: 'posto-extension',
    demandType: 'Regularização',
    sphere: 'Federal',
    agencies: ['ANP'],
    complexity: 'Baixa',
    professionals: ['Analista regulatório', 'Assistente documental'],
    deliverableType: 'Dossiê de regularização',
    precoBase: 2200,
    precoMin: 1400,
    precoMax: 4200,
    custoInterno: 900,
    margem: 59,
    fluxo: 'pontual',
    requerDiagnostico: false,
    orcamentoDireto: true,
  },
  {
    codigo: 'PST-ANP-002',
    nome: 'Gestão de calibração e aferição de bombas',
    descricao: 'Planejamento, acompanhamento e consolidação documental da aferição metrológica de bombas e bicos.',
    categoria: 'Gestão e Consultoria Ambiental',
    subcategoria: 'Regulação ANP',
    horasTecnicasBase: 8,
    fatorComplexidade: 0.8,
    valorReferenciaHora: 170,
    obrigacaoBaseCodigo: 'ANP-002',
    fonte: 'posto-extension',
    demandType: 'Operação / Contínuo',
    sphere: 'Federal',
    agencies: ['INMETRO', 'IPEM'],
    complexity: 'Baixa',
    professionals: ['Técnico operacional', 'Analista regulatório'],
    deliverableType: 'Checklist e evidências',
    precoBase: 1600,
    precoMin: 900,
    precoMax: 3000,
    custoInterno: 700,
    margem: 56,
    fluxo: 'continuo',
    requerDiagnostico: false,
    orcamentoDireto: true,
  },
  {
    codigo: 'PST-ANP-003',
    nome: 'Gestão mensal de SCANC e estoque regulatório',
    descricao: 'Conferência, fechamento e envio dos dados de movimentação de combustíveis nos sistemas regulatórios aplicáveis.',
    categoria: 'Gestão e Consultoria Ambiental',
    subcategoria: 'Regulação ANP',
    horasTecnicasBase: 4,
    fatorComplexidade: 0.8,
    valorReferenciaHora: 150,
    obrigacaoBaseCodigo: 'ANP-003',
    fonte: 'posto-extension',
    demandType: 'Operação / Contínuo',
    sphere: 'Federal',
    agencies: ['ANP'],
    complexity: 'Baixa',
    professionals: ['Assistente administrativo', 'Analista regulatório'],
    deliverableType: 'Comprovante de envio e conferência',
    precoBase: 900,
    precoMin: 600,
    precoMax: 1800,
    custoInterno: 380,
    margem: 58,
    fluxo: 'continuo',
    requerDiagnostico: false,
    orcamentoDireto: true,
  },
  {
    codigo: 'PST-ANP-004',
    nome: 'Gestão de qualidade de combustíveis e contraprovas',
    descricao: 'Implantação e acompanhamento do fluxo de coleta, guarda de amostras, laudos e resposta a fiscalização de qualidade.',
    categoria: 'Gestão e Consultoria Ambiental',
    subcategoria: 'Regulação ANP',
    horasTecnicasBase: 10,
    fatorComplexidade: 0.9,
    valorReferenciaHora: 180,
    obrigacaoBaseCodigo: 'ANP-004',
    fonte: 'posto-extension',
    demandType: 'Operação / Contínuo',
    sphere: 'Federal',
    agencies: ['ANP', 'Laboratório credenciado'],
    complexity: 'Média',
    professionals: ['Analista regulatório', 'Técnico operacional'],
    deliverableType: 'Procedimento e evidências',
    precoBase: 2200,
    precoMin: 1400,
    precoMax: 4200,
    custoInterno: 1000,
    margem: 55,
    fluxo: 'continuo',
    requerDiagnostico: false,
    orcamentoDireto: true,
  },
  {
    codigo: 'PST-SST-001',
    nome: 'Programa de Gerenciamento de Riscos (PGR)',
    descricao: 'Estruturação e revisão do PGR com inventário de riscos, plano de ação e evidências para operação do posto.',
    categoria: 'Gestão e Consultoria Ambiental',
    subcategoria: 'SST',
    horasTecnicasBase: 24,
    fatorComplexidade: 1,
    valorReferenciaHora: 190,
    obrigacaoBaseCodigo: 'SST-001',
    fonte: 'posto-extension',
    demandType: 'Plano técnico',
    sphere: 'Federal',
    agencies: ['MTE'],
    complexity: 'Média',
    professionals: ['Engenheiro de segurança', 'Técnico de segurança'],
    deliverableType: 'Programa técnico',
    precoBase: 4600,
    precoMin: 3000,
    precoMax: 8200,
    custoInterno: 2100,
    margem: 54,
    fluxo: 'pontual',
    requerDiagnostico: true,
    orcamentoDireto: true,
  },
  {
    codigo: 'PST-SST-002',
    nome: 'PCMSO e coordenação de saúde ocupacional',
    descricao: 'Coordenação documental e técnica do PCMSO, exames periódicos e integração com medicina do trabalho.',
    categoria: 'Gestão e Consultoria Ambiental',
    subcategoria: 'SST',
    horasTecnicasBase: 16,
    fatorComplexidade: 1,
    valorReferenciaHora: 200,
    obrigacaoBaseCodigo: 'SST-002',
    fonte: 'posto-extension',
    demandType: 'Programa técnico',
    sphere: 'Federal',
    agencies: ['MTE'],
    complexity: 'Média',
    professionals: ['Médico do trabalho', 'Técnico de segurança'],
    deliverableType: 'Programa e cronograma',
    precoBase: 3600,
    precoMin: 2400,
    precoMax: 7000,
    custoInterno: 1700,
    margem: 53,
    fluxo: 'pontual',
    requerDiagnostico: true,
    orcamentoDireto: true,
  },
  {
    codigo: 'PST-SST-003',
    nome: 'Gestão de ASO e exames ocupacionais',
    descricao: 'Controle de vencimentos, agendamento, evidências e conformidade dos ASOs por colaborador.',
    categoria: 'Gestão e Consultoria Ambiental',
    subcategoria: 'SST',
    horasTecnicasBase: 6,
    fatorComplexidade: 0.8,
    valorReferenciaHora: 150,
    obrigacaoBaseCodigo: 'SST-003',
    fonte: 'posto-extension',
    demandType: 'Operação / Contínuo',
    sphere: 'Federal',
    agencies: ['MTE', 'Clínica ocupacional'],
    complexity: 'Baixa',
    professionals: ['Assistente SST', 'Técnico de segurança'],
    deliverableType: 'Controle e evidências',
    precoBase: 1200,
    precoMin: 700,
    precoMax: 2400,
    custoInterno: 500,
    margem: 58,
    fluxo: 'continuo',
    requerDiagnostico: false,
    orcamentoDireto: true,
  },
  {
    codigo: 'PST-SST-004',
    nome: 'Laudo de insalubridade e periculosidade',
    descricao: 'Coordenação técnica da avaliação e emissão de laudo para funções expostas a inflamáveis e agentes ocupacionais.',
    categoria: 'Gestão e Consultoria Ambiental',
    subcategoria: 'SST',
    horasTecnicasBase: 14,
    fatorComplexidade: 1,
    valorReferenciaHora: 220,
    obrigacaoBaseCodigo: 'SST-004',
    fonte: 'posto-extension',
    demandType: 'Laudo técnico',
    sphere: 'Federal',
    agencies: ['MTE'],
    complexity: 'Média',
    professionals: ['Engenheiro de segurança'],
    deliverableType: 'Laudo técnico',
    precoBase: 3200,
    precoMin: 2200,
    precoMax: 6200,
    custoInterno: 1500,
    margem: 53,
    fluxo: 'pontual',
    requerDiagnostico: false,
    orcamentoDireto: true,
  },
  {
    codigo: 'PST-SST-005',
    nome: 'Treinamento de brigada e primeiros socorros',
    descricao: 'Planejamento, agenda, evidências e consolidação documental do treinamento de brigada para o posto.',
    categoria: 'Gestão e Consultoria Ambiental',
    subcategoria: 'SST',
    horasTecnicasBase: 10,
    fatorComplexidade: 0.9,
    valorReferenciaHora: 180,
    obrigacaoBaseCodigo: 'SST-005',
    fonte: 'posto-extension',
    demandType: 'Treinamento',
    sphere: 'Estadual',
    agencies: ['Corpo de Bombeiros'],
    complexity: 'Média',
    professionals: ['Instrutor brigadista', 'Engenheiro de segurança'],
    deliverableType: 'Certificados e lista de presença',
    precoBase: 2400,
    precoMin: 1600,
    precoMax: 4600,
    custoInterno: 1100,
    margem: 54,
    fluxo: 'pontual',
    requerDiagnostico: false,
    orcamentoDireto: true,
  },
  {
    codigo: 'PST-SST-006',
    nome: 'Treinamento NR-20 para operação de posto',
    descricao: 'Coordenação e evidência do treinamento NR-20 para frentistas, operadores e equipes expostas.',
    categoria: 'Gestão e Consultoria Ambiental',
    subcategoria: 'SST',
    horasTecnicasBase: 12,
    fatorComplexidade: 0.9,
    valorReferenciaHora: 190,
    obrigacaoBaseCodigo: 'SST-006',
    fonte: 'posto-extension',
    demandType: 'Treinamento',
    sphere: 'Federal',
    agencies: ['MTE'],
    complexity: 'Média',
    professionals: ['Instrutor NR-20', 'Técnico de segurança'],
    deliverableType: 'Certificados e plano de turma',
    precoBase: 2800,
    precoMin: 1800,
    precoMax: 5200,
    custoInterno: 1300,
    margem: 54,
    fluxo: 'pontual',
    requerDiagnostico: false,
    orcamentoDireto: true,
  },
  {
    codigo: 'PST-URB-001',
    nome: 'Renovação de AVCB e adequação documental',
    descricao: 'Condução documental e técnica da renovação do AVCB, com checklist de pendências e interface com bombeiros.',
    categoria: 'Gestão e Consultoria Ambiental',
    subcategoria: 'Urbanístico e Bombeiros',
    horasTecnicasBase: 18,
    fatorComplexidade: 1,
    valorReferenciaHora: 200,
    obrigacaoBaseCodigo: 'URB-001',
    fonte: 'posto-extension',
    demandType: 'Regularização',
    sphere: 'Estadual',
    agencies: ['Corpo de Bombeiros'],
    complexity: 'Média',
    professionals: ['Engenheiro', 'Analista regulatório'],
    deliverableType: 'Dossiê e plano de adequação',
    precoBase: 4200,
    precoMin: 2800,
    precoMax: 7800,
    custoInterno: 1900,
    margem: 55,
    fluxo: 'pontual',
    requerDiagnostico: true,
    orcamentoDireto: false,
  },
  {
    codigo: 'PST-URB-002',
    nome: 'Renovação de alvará de funcionamento',
    descricao: 'Gestão documental e interface com prefeitura para renovação anual do alvará do estabelecimento.',
    categoria: 'Gestão e Consultoria Ambiental',
    subcategoria: 'Urbanístico e Bombeiros',
    horasTecnicasBase: 8,
    fatorComplexidade: 0.8,
    valorReferenciaHora: 170,
    obrigacaoBaseCodigo: 'URB-002',
    fonte: 'posto-extension',
    demandType: 'Regularização',
    sphere: 'Municipal',
    agencies: ['Prefeitura'],
    complexity: 'Baixa',
    professionals: ['Assistente documental', 'Analista regulatório'],
    deliverableType: 'Protocolo e evidências',
    precoBase: 1600,
    precoMin: 1000,
    precoMax: 3200,
    custoInterno: 700,
    margem: 56,
    fluxo: 'pontual',
    requerDiagnostico: false,
    orcamentoDireto: true,
  },
  {
    codigo: 'PST-URB-003',
    nome: 'Licença sanitária para conveniência e alimentação',
    descricao: 'Estruturação técnica e documental para licenciamento sanitário de loja de conveniência e áreas de alimentação do posto.',
    categoria: 'Gestão e Consultoria Ambiental',
    subcategoria: 'Urbanístico e Bombeiros',
    horasTecnicasBase: 10,
    fatorComplexidade: 0.9,
    valorReferenciaHora: 180,
    obrigacaoBaseCodigo: 'URB-003',
    fonte: 'posto-extension',
    demandType: 'Regularização',
    sphere: 'Municipal',
    agencies: ['Vigilância Sanitária'],
    complexity: 'Baixa',
    professionals: ['Sanitarista', 'Analista regulatório'],
    deliverableType: 'Dossiê técnico',
    precoBase: 2200,
    precoMin: 1400,
    precoMax: 4200,
    custoInterno: 950,
    margem: 57,
    fluxo: 'pontual',
    requerDiagnostico: false,
    orcamentoDireto: true,
  },
  {
    codigo: 'PST-URB-004',
    nome: 'Gestão de manutenção e certificação de extintores',
    descricao: 'Planejamento, controle de vencimentos e evidência de manutenção dos extintores do posto.',
    categoria: 'Gestão e Consultoria Ambiental',
    subcategoria: 'Urbanístico e Bombeiros',
    horasTecnicasBase: 4,
    fatorComplexidade: 0.8,
    valorReferenciaHora: 150,
    obrigacaoBaseCodigo: 'URB-004',
    fonte: 'posto-extension',
    demandType: 'Operação / Contínuo',
    sphere: 'Estadual',
    agencies: ['Corpo de Bombeiros'],
    complexity: 'Baixa',
    professionals: ['Assistente operacional'],
    deliverableType: 'Controle e laudos',
    precoBase: 900,
    precoMin: 600,
    precoMax: 1800,
    custoInterno: 380,
    margem: 58,
    fluxo: 'continuo',
    requerDiagnostico: false,
    orcamentoDireto: true,
  },
  {
    codigo: 'PST-URB-005',
    nome: 'Laudo elétrico e SPDA para área classificada',
    descricao: 'Coordenação técnica da inspeção elétrica, SPDA e aterramento com emissão de laudo e ART.',
    categoria: 'Gestão e Consultoria Ambiental',
    subcategoria: 'Urbanístico e Bombeiros',
    horasTecnicasBase: 16,
    fatorComplexidade: 1,
    valorReferenciaHora: 220,
    obrigacaoBaseCodigo: 'URB-005',
    fonte: 'posto-extension',
    demandType: 'Laudo técnico',
    sphere: 'Estadual / Municipal',
    agencies: ['Corpo de Bombeiros', 'Prefeitura'],
    complexity: 'Média',
    professionals: ['Engenheiro eletricista'],
    deliverableType: 'Laudo técnico e ART',
    precoBase: 3800,
    precoMin: 2600,
    precoMax: 7200,
    custoInterno: 1800,
    margem: 53,
    fluxo: 'pontual',
    requerDiagnostico: false,
    orcamentoDireto: true,
  },
  {
    codigo: 'PST-URB-006',
    nome: 'ART/RRT anual de acompanhamento técnico',
    descricao: 'Emissão e controle de ART/RRT anual do responsável técnico pelas instalações e operação regulatória do posto.',
    categoria: 'Gestão e Consultoria Ambiental',
    subcategoria: 'Urbanístico e Bombeiros',
    horasTecnicasBase: 4,
    fatorComplexidade: 0.8,
    valorReferenciaHora: 180,
    obrigacaoBaseCodigo: 'URB-006',
    fonte: 'posto-extension',
    demandType: 'Documento técnico',
    sphere: 'Federal',
    agencies: ['CREA', 'CAU', 'CFT'],
    complexity: 'Baixa',
    professionals: ['Responsável técnico'],
    deliverableType: 'ART ou RRT',
    precoBase: 1100,
    precoMin: 700,
    precoMax: 2200,
    custoInterno: 480,
    margem: 56,
    fluxo: 'pontual',
    requerDiagnostico: false,
    orcamentoDireto: true,
  },
  {
    codigo: 'MON-008',
    nome: 'Monitoramento de Água Subterrânea',
    descricao: 'Monitoramento de qualidade de água subterrânea.',
    categoria: 'Monitoramento Ambiental',
    subcategoria: 'Meio Físico',
    horasTecnicasBase: 16,
    fatorComplexidade: 1,
    valorReferenciaHora: 200,
    obrigacaoBaseCodigo: 'MON-001',
    fonte: 'enviro-clarity-main',
    codigoOrigem: 'MON-74',
    demandType: 'Operação / Contínuo',
    sphere: 'Estadual / Municipal',
    agencies: ['Órgão licenciador', 'Laboratório'],
    complexity: 'Média',
    professionals: ['Engenheiro ambiental', 'Técnico'],
    deliverableType: 'Relatório de monitoramento',
    precoBase: 4500,
    precoMin: 2800,
    precoMax: 9000,
    custoInterno: 1800,
    margem: 60,
    fluxo: 'continuo',
    requerDiagnostico: false,
    orcamentoDireto: true,
  },
  {
    codigo: 'PST-MON-002',
    nome: 'Relatório de monitoramento ambiental ao órgão licenciador',
    descricao: 'Consolidação técnica das campanhas, laudos e evidências para atendimento das condicionantes de monitoramento.',
    categoria: 'Monitoramento Ambiental',
    subcategoria: 'Relatórios e condicionantes',
    horasTecnicasBase: 12,
    fatorComplexidade: 0.9,
    valorReferenciaHora: 190,
    obrigacaoBaseCodigo: 'MON-002',
    fonte: 'posto-extension',
    demandType: 'Operação / Contínuo',
    sphere: 'Estadual / Municipal',
    agencies: ['Órgão licenciador'],
    complexity: 'Média',
    professionals: ['Engenheiro ambiental', 'Analista regulatório'],
    deliverableType: 'Relatório técnico',
    precoBase: 2600,
    precoMin: 1800,
    precoMax: 5200,
    custoInterno: 1200,
    margem: 54,
    fluxo: 'continuo',
    requerDiagnostico: false,
    orcamentoDireto: true,
  },
  {
    codigo: 'OUT-013',
    nome: 'Monitoramento de Nível Freático (Piezometria)',
    descricao: 'Monitoramento de nível freático por piezometria.',
    categoria: 'Recursos Hídricos e Outorga',
    subcategoria: 'Estudos Hidrológicos',
    horasTecnicasBase: 12,
    fatorComplexidade: 0.8,
    valorReferenciaHora: 180,
    obrigacaoBaseCodigo: 'MON-003',
    fonte: 'enviro-clarity-main',
    codigoOrigem: 'HID-33',
    demandType: 'Operação / Contínuo',
    sphere: 'Estadual / Federal',
    agencies: ['SEMAD-GO', 'ANA'],
    complexity: 'Baixa',
    professionals: ['Técnico ambiental'],
    deliverableType: 'Relatório de monitoramento',
    precoBase: 2000,
    precoMin: 1200,
    precoMax: 4000,
    custoInterno: 800,
    margem: 60,
    fluxo: 'continuo',
    requerDiagnostico: false,
    orcamentoDireto: true,
  },
  {
    codigo: 'OUT-015',
    nome: 'Outorga de Direito de Uso da Água — Captação Subterrânea',
    descricao: 'Obter autorização legal para captação de água de poço tubular profundo.',
    categoria: 'Recursos Hídricos e Outorga',
    subcategoria: 'Outorga de Uso da Água',
    horasTecnicasBase: 40,
    fatorComplexidade: 1.2,
    valorReferenciaHora: 200,
    obrigacaoBaseCodigo: 'MON-004',
    fonte: 'enviro-clarity-main',
    codigoOrigem: 'HID-02',
    demandType: 'Novo processo / Regularização',
    sphere: 'Estadual / Federal',
    agencies: ['SEMAD-GO', 'ANA', 'SIGARH/Veredas', 'SEMARH'],
    complexity: 'Média',
    professionals: ['Engenheiro ambiental'],
    deliverableType: 'Portaria de Outorga',
    precoBase: 6000,
    precoMin: 3500,
    precoMax: 12000,
    custoInterno: 2500,
    margem: 58,
    fluxo: 'pontual',
    requerDiagnostico: true,
    orcamentoDireto: false,
  },
  {
    codigo: 'PST-LOG-001',
    nome: 'Gestão de OLUC e MTR',
    descricao: 'Controle da coleta, evidências, MTR e rastreabilidade do óleo lubrificante usado e contaminado.',
    categoria: 'Gestão e Consultoria Ambiental',
    subcategoria: 'Logística reversa',
    horasTecnicasBase: 6,
    fatorComplexidade: 0.8,
    valorReferenciaHora: 160,
    obrigacaoBaseCodigo: 'LOG-001',
    fonte: 'posto-extension',
    demandType: 'Operação / Contínuo',
    sphere: 'Federal',
    agencies: ['SINIR', 'Transportadora licenciada'],
    complexity: 'Baixa',
    professionals: ['Assistente ambiental', 'Analista operacional'],
    deliverableType: 'MTR e evidências',
    precoBase: 1200,
    precoMin: 700,
    precoMax: 2400,
    custoInterno: 520,
    margem: 57,
    fluxo: 'continuo',
    requerDiagnostico: false,
    orcamentoDireto: true,
  },
  {
    codigo: 'PST-LOG-002',
    nome: 'Gestão de destinação de filtros de óleo',
    descricao: 'Controle de armazenamento, coleta, MTR e comprovantes de destinação dos filtros usados.',
    categoria: 'Gestão e Consultoria Ambiental',
    subcategoria: 'Logística reversa',
    horasTecnicasBase: 5,
    fatorComplexidade: 0.8,
    valorReferenciaHora: 160,
    obrigacaoBaseCodigo: 'LOG-002',
    fonte: 'posto-extension',
    demandType: 'Operação / Contínuo',
    sphere: 'Federal',
    agencies: ['SINIR', 'Transportadora licenciada'],
    complexity: 'Baixa',
    professionals: ['Assistente ambiental'],
    deliverableType: 'MTR e comprovantes',
    precoBase: 1000,
    precoMin: 600,
    precoMax: 2200,
    custoInterno: 450,
    margem: 55,
    fluxo: 'continuo',
    requerDiagnostico: false,
    orcamentoDireto: true,
  },
  {
    codigo: 'PST-LOG-003',
    nome: 'Gestão de devolução de embalagens de lubrificantes',
    descricao: 'Organização do fluxo de devolução, comprovantes e rastreabilidade das embalagens pós-consumo.',
    categoria: 'Gestão e Consultoria Ambiental',
    subcategoria: 'Logística reversa',
    horasTecnicasBase: 4,
    fatorComplexidade: 0.8,
    valorReferenciaHora: 150,
    obrigacaoBaseCodigo: 'LOG-003',
    fonte: 'posto-extension',
    demandType: 'Operação / Contínuo',
    sphere: 'Federal',
    agencies: ['Sistema de logística reversa'],
    complexity: 'Baixa',
    professionals: ['Assistente operacional'],
    deliverableType: 'Comprovantes e controle',
    precoBase: 900,
    precoMin: 500,
    precoMax: 1800,
    custoInterno: 380,
    margem: 58,
    fluxo: 'continuo',
    requerDiagnostico: false,
    orcamentoDireto: true,
  },
  {
    codigo: 'PST-LOG-004',
    nome: 'Gestão de destinação de pneus inservíveis',
    descricao: 'Controle do fluxo de coleta, comprovantes e atendimento às exigências de destinação ambientalmente adequada.',
    categoria: 'Gestão e Consultoria Ambiental',
    subcategoria: 'Logística reversa',
    horasTecnicasBase: 4,
    fatorComplexidade: 0.8,
    valorReferenciaHora: 150,
    obrigacaoBaseCodigo: 'LOG-004',
    fonte: 'posto-extension',
    demandType: 'Operação / Contínuo',
    sphere: 'Federal',
    agencies: ['Reciclanip', 'Coletor licenciado'],
    complexity: 'Baixa',
    professionals: ['Assistente operacional'],
    deliverableType: 'Comprovantes e controle',
    precoBase: 900,
    precoMin: 500,
    precoMax: 1800,
    custoInterno: 380,
    margem: 58,
    fluxo: 'continuo',
    requerDiagnostico: false,
    orcamentoDireto: true,
  },
  {
    codigo: 'PST-LOG-005',
    nome: 'Declaração anual de resíduos e consolidação SIGOR/SINIR',
    descricao: 'Fechamento anual de geração e destinação de resíduos com consolidação documental e protocolo em sistema aplicável.',
    categoria: 'Gestão e Consultoria Ambiental',
    subcategoria: 'Logística reversa',
    horasTecnicasBase: 8,
    fatorComplexidade: 0.9,
    valorReferenciaHora: 170,
    obrigacaoBaseCodigo: 'LOG-005',
    fonte: 'posto-extension',
    demandType: 'Operação / Contínuo',
    sphere: 'Federal / Estadual',
    agencies: ['SIGOR', 'SINIR'],
    complexity: 'Baixa',
    professionals: ['Analista ambiental', 'Assistente administrativo'],
    deliverableType: 'Declaração e protocolo',
    precoBase: 1700,
    precoMin: 1000,
    precoMax: 3200,
    custoInterno: 760,
    margem: 55,
    fluxo: 'continuo',
    requerDiagnostico: false,
    orcamentoDireto: true,
  },
]

function buildMetadata(servico: ServicoSeed) {
  return {
    fonteCatalogo: servico.fonte,
    codigoOrigem: servico.codigoOrigem ?? null,
    demandType: servico.demandType ?? null,
    sphere: servico.sphere ?? null,
    agencies: servico.agencies ?? [],
    complexity: servico.complexity ?? null,
    professionals: servico.professionals ?? [],
    deliverableType: servico.deliverableType ?? null,
    pricingReference: {
      basePrice: servico.precoBase ?? null,
      minPrice: servico.precoMin ?? null,
      maxPrice: servico.precoMax ?? null,
      internalCost: servico.custoInterno ?? null,
      margin: servico.margem ?? null,
    },
    flowType: servico.fluxo ?? 'pontual',
    requiresDiagnostic: servico.requerDiagnostico ?? true,
    allowDirectBudget: servico.orcamentoDireto ?? false,
    seededAt: '2026-05-11',
  }
}

export async function seedServicosConsultoriaEPrecificacao(prisma: PrismaClient, tenantId: string) {
  console.log('🌱 Seeding catálogo de serviços consultivos e política de precificação...')

  const codigosObrigacao = [...new Set(SERVICOS.map((servico) => servico.obrigacaoBaseCodigo).filter(Boolean))] as string[]
  const obrigacoes = await prisma.obrigacaoRegulatoriaBase.findMany({
    where: { codigo: { in: codigosObrigacao } },
    select: { id: true, codigo: true },
  })

  const obrigacaoPorCodigo = new Map(obrigacoes.map((obrigacao) => [obrigacao.codigo, obrigacao.id]))
  const codigosAusentes = codigosObrigacao.filter((codigo) => !obrigacaoPorCodigo.has(codigo))
  if (codigosAusentes.length > 0) {
    throw new Error(`Obrigações regulatórias ausentes para seed de serviços: ${codigosAusentes.join(', ')}`)
  }

  let criados = 0
  let atualizados = 0

  for (const servico of SERVICOS) {
    const obrigacaoBaseId = servico.obrigacaoBaseCodigo
      ? obrigacaoPorCodigo.get(servico.obrigacaoBaseCodigo) ?? null
      : null

    const data = {
      codigo: servico.codigo,
      nome: servico.nome,
      descricao: servico.descricao,
      categoria: servico.categoria,
      subcategoria: servico.subcategoria ?? null,
      horasTecnicasBase: servico.horasTecnicasBase,
      fatorComplexidade: servico.fatorComplexidade,
      valorReferenciaHora: servico.valorReferenciaHora,
      precoBase: servico.precoBase ?? null,
      precoMinimo: servico.precoMin ?? null,
      precoMaximo: servico.precoMax ?? null,
      custoInternoEstimado: servico.custoInterno ?? null,
      margemLucroAlvo: servico.margem ?? null,
      recorrente: servico.fluxo === 'continuo',
      mesesRecorrencia: servico.fluxo === 'continuo' ? 12 : null,
      obrigacaoBaseId,
      obrigacaoBaseCodigo: servico.obrigacaoBaseCodigo ?? null,
      metadata: buildMetadata(servico),
      ativo: true,
    }

    const existente = await prisma.servicoCatalogo.findUnique({
      where: { codigo: servico.codigo },
      select: { id: true },
    })

    if (existente) {
      await prisma.servicoCatalogo.update({
        where: { codigo: servico.codigo },
        data,
      })
      atualizados += 1
      continue
    }

    await prisma.servicoCatalogo.create({ data })
    criados += 1
  }

  await prisma.politicaPrecificacaoDiagnostico.upsert({
    where: { tenantId },
    update: {
      nome: 'Padrao Posto Compliance',
      portePequenoMultiplier: 0.9,
      porteMedioMultiplier: 1.15,
      porteGrandeMultiplier: 1.4,
      situacaoImplantacaoMultiplier: 1.1,
      situacaoOperacaoMultiplier: 1,
      situacaoIrregularMultiplier: 1.3,
      situacaoAmpliacaoMultiplier: 1.15,
      potencialAltoMultiplier: 1.1,
      potencialMuitoAltoMultiplier: 1.2,
      areaMediaMultiplier: 1.1,
      areaGrandeMultiplier: 1.2,
      descontoCategoria3Plus: 0.1,
      descontoVolume5Plus: 0.05,
      descontoMaximo: 0.15,
      validadePropostaDias: 30,
      ativo: true,
      metadata: {
        sourceCatalog: 'enviro-clarity-main',
        pricingStrategy: 'posto-compliance-v1',
        notes: 'Multiplicadores iniciais para diagnóstico, orçamento e composição de proposta em operações de postos.',
        seededAt: '2026-05-11',
      },
    },
    create: {
      tenantId,
      nome: 'Padrao Posto Compliance',
      portePequenoMultiplier: 0.9,
      porteMedioMultiplier: 1.15,
      porteGrandeMultiplier: 1.4,
      situacaoImplantacaoMultiplier: 1.1,
      situacaoOperacaoMultiplier: 1,
      situacaoIrregularMultiplier: 1.3,
      situacaoAmpliacaoMultiplier: 1.15,
      potencialAltoMultiplier: 1.1,
      potencialMuitoAltoMultiplier: 1.2,
      areaMediaMultiplier: 1.1,
      areaGrandeMultiplier: 1.2,
      descontoCategoria3Plus: 0.1,
      descontoVolume5Plus: 0.05,
      descontoMaximo: 0.15,
      validadePropostaDias: 30,
      metadata: {
        sourceCatalog: 'enviro-clarity-main',
        pricingStrategy: 'posto-compliance-v1',
        notes: 'Multiplicadores iniciais para diagnóstico, orçamento e composição de proposta em operações de postos.',
        seededAt: '2026-05-11',
      },
    },
  })

  console.log(`✅ Serviços consultivos: ${criados} criados, ${atualizados} atualizados (total: ${SERVICOS.length})`)
  console.log('✅ Política de precificação do diagnóstico: configurada para o tenant')
}
