import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

type ServicoSeed = {
  codigo: string
  nome: string
  descricao: string
  categoria: string
  subcategoria?: string
  horasTecnicasBase: number
  fatorComplexidade: number
  valorReferenciaHora: number
  obrigacaoBaseCodigo?: string
  fonte: 'enviro-clarity-main' | 'posto-extension'
  codigoOrigem?: string
  demandType?: string
  sphere?: string
  agencies?: string[]
  complexity?: 'Baixa' | 'Média' | 'Alta'
  professionals?: string[]
  deliverableType?: string
  precoBase?: number
  precoMin?: number
  precoMax?: number
  custoInterno?: number
  margem?: number
  fluxo?: 'pontual' | 'continuo'
  requerDiagnostico?: boolean
  orcamentoDireto?: boolean
  metadata?: any
}

/**
 * Catálogo Base da INTERFACE (Habilis)
 * Mapeado do arquivo legacy: enviro-clarity-main/src/lib/habilis-services.ts
 */
const SERVICOS_BASE: ServicoSeed[] = [
  // ─── LICENCIAMENTO AMBIENTAL ────────────────────────────
  {
    codigo: 'LIC-001',
    nome: 'Memorial de Caracterização do Empreendimento (MCE)',
    descricao: 'Elaboração de memorial técnico contendo caracterização locacional, operacional, produtiva e ambiental do empreendimento para instrução de processos de licenciamento ambiental.',
    categoria: 'Licenciamento Ambiental',
    subcategoria: 'Estudos Técnicos',
    horasTecnicasBase: 8,
    fatorComplexidade: 1.0,
    valorReferenciaHora: 200,
    fonte: 'enviro-clarity-main',
    codigoOrigem: 'LIC-001',
    demandType: 'Novo licenciamento / Renovação',
    sphere: 'Estadual / Municipal',
    agencies: ['AMMA', 'SEMAD-GO', 'Prefeitura', 'IBAMA'],
    complexity: 'Baixa',
    professionals: ['Engenheiro Ambiental', 'Biólogo', 'Geógrafo'],
    deliverableType: 'Produto cartográfico',
    precoBase: 3000,
    precoMin: 1500,
    precoMax: 5000,
    custoInterno: 1200,
    margem: 60,
    fluxo: 'pontual',
    requerDiagnostico: true,
    orcamentoDireto: false,
    metadata: {
      whenToApply: 'Início de qualquer processo de licenciamento',
      triggers: 'Novo licenciamento, regularização, renovação',
      referenceTimeline: '5–10 dias úteis',
      steps: 'Coleta de dados → Visita técnica → Elaboração → Revisão → Entrega'
    }
  },
  {
    codigo: 'LIC-002',
    nome: 'Estudo Ambiental Simplificado (EAS)',
    descricao: 'Elaboração de estudo ambiental simplificado para empreendimentos de pequeno ou médio potencial de impacto, incluindo diagnóstico ambiental e proposição de medidas mitigadoras.',
    categoria: 'Licenciamento Ambiental',
    subcategoria: 'Estudos Técnicos',
    horasTecnicasBase: 24,
    fatorComplexidade: 1.0,
    valorReferenciaHora: 200,
    fonte: 'enviro-clarity-main',
    codigoOrigem: 'LIC-002',
    demandType: 'Novo licenciamento',
    sphere: 'Estadual / Municipal',
    agencies: ['AMMA', 'SEMAD-GO', 'IBAMA'],
    complexity: 'Média',
    professionals: ['Engenheiro Ambiental', 'Biólogo', 'Geógrafo'],
    deliverableType: 'Estudo ambiental',
    precoBase: 8000,
    precoMin: 5000,
    precoMax: 15000,
    custoInterno: 3500,
    margem: 56,
    fluxo: 'pontual',
    requerDiagnostico: true,
    orcamentoDireto: false,
    metadata: {
      whenToApply: 'Empreendimentos de médio potencial poluidor',
      triggers: 'CNAE com potencial poluidor médio, exigência do órgão',
      referenceTimeline: '15–30 dias úteis'
    }
  },
  {
    codigo: 'LIC-003',
    nome: 'Relatório Ambiental Simplificado (RAS)',
    descricao: 'Relatório técnico para regularização ambiental de empreendimentos com impacto moderado, incluindo diagnóstico, avaliação de impactos e medidas corretivas.',
    categoria: 'Licenciamento Ambiental',
    subcategoria: 'Estudos Técnicos',
    horasTecnicasBase: 20,
    fatorComplexidade: 1.0,
    valorReferenciaHora: 200,
    fonte: 'enviro-clarity-main',
    codigoOrigem: 'LIC-003',
    demandType: 'Regularização',
    sphere: 'Estadual / Municipal',
    agencies: ['AMMA', 'SEMAD-GO', 'IBAMA'],
    complexity: 'Média',
    professionals: ['Engenheiro Ambiental', 'Biólogo'],
    deliverableType: 'Estudo ambiental',
    precoBase: 7000,
    precoMin: 4000,
    precoMax: 12000,
    custoInterno: 3000,
    margem: 57,
    fluxo: 'pontual',
    requerDiagnostico: true,
    orcamentoDireto: false
  },
  {
    codigo: 'LIC-004',
    nome: 'Relatório de Controle Ambiental (RCA)',
    descricao: 'Relatório técnico com diagnóstico ambiental detalhado, avaliação de impactos e definição de medidas de controle ambiental para subsidiar licenciamento.',
    categoria: 'Licenciamento Ambiental',
    subcategoria: 'Estudos Técnicos',
    horasTecnicasBase: 24,
    fatorComplexidade: 1.0,
    valorReferenciaHora: 200,
    fonte: 'enviro-clarity-main',
    codigoOrigem: 'LIC-004',
    demandType: 'Novo licenciamento / Ampliação',
    sphere: 'Estadual / Municipal',
    agencies: ['SEMAD-GO', 'AMMA', 'IBAMA'],
    complexity: 'Média',
    professionals: ['Engenheiro Ambiental', 'Biólogo', 'Geógrafo'],
    deliverableType: 'Relatório técnico',
    precoBase: 8000,
    precoMin: 5000,
    precoMax: 14000,
    custoInterno: 3500,
    margem: 56,
    fluxo: 'pontual',
    requerDiagnostico: true,
    orcamentoDireto: false
  },
  {
    codigo: 'LIC-005',
    nome: 'Estudo de Impacto Ambiental (EIA)',
    descricao: 'Estudo ambiental completo para empreendimentos de significativa degradação ambiental, incluindo diagnóstico dos meios físico, biótico e socioeconômico.',
    categoria: 'Licenciamento Ambiental',
    subcategoria: 'Estudos Técnicos',
    horasTecnicasBase: 160,
    fatorComplexidade: 1.5,
    valorReferenciaHora: 250,
    fonte: 'enviro-clarity-main',
    codigoOrigem: 'LIC-005',
    demandType: 'Novo licenciamento / Renovação',
    sphere: 'Estadual / Municipal',
    agencies: ['SEMAD-GO', 'IBAMA', 'Prefeituras'],
    complexity: 'Alta',
    professionals: ['Equipe multidisciplinar'],
    deliverableType: 'Estudo ambiental',
    precoBase: 80000,
    precoMin: 40000,
    precoMax: 200000,
    custoInterno: 35000,
    margem: 56,
    fluxo: 'pontual',
    requerDiagnostico: true,
    orcamentoDireto: false,
    metadata: {
      whenToApply: 'Empreendimentos de alto potencial poluidor or grande porte',
      triggers: 'CNAE alto impacto, grande porte, exigência legal',
      referenceTimeline: '60–120 dias úteis',
      commercialNotes: 'Escopo variável conforme TR do órgão. Pode exigir equipe multidisciplinar extensa.'
    }
  },
  {
    codigo: 'LIC-006',
    nome: 'Relatório de Impacto Ambiental (RIMA)',
    descricao: 'Relatório de impacto derivado do EIA em linguagem acessível ao público para audiências públicas e análise social.',
    categoria: 'Licenciamento Ambiental',
    subcategoria: 'Estudos Técnicos',
    horasTecnicasBase: 40,
    fatorComplexidade: 1.0,
    valorReferenciaHora: 200,
    fonte: 'enviro-clarity-main',
    codigoOrigem: 'LIC-006',
    demandType: 'Andamento de processo',
    sphere: 'Estadual / Municipal',
    agencies: ['SEMAD-GO', 'IBAMA'],
    complexity: 'Média',
    professionals: ['Equipe multidisciplinar'],
    deliverableType: 'Estudo ambiental',
    precoBase: 20000,
    precoMin: 12000,
    precoMax: 40000,
    custoInterno: 8000,
    margem: 60,
    fluxo: 'pontual',
    requerDiagnostico: true,
    orcamentoDireto: false
  },
  {
    codigo: 'LIC-007',
    nome: 'Relatório Ambiental Preliminar (RAP)',
    descricao: 'Estudo ambiental preliminar para avaliação inicial de viabilidade ambiental e indicação de estudos complementares.',
    categoria: 'Licenciamento Ambiental',
    subcategoria: 'Estudos Técnicos',
    horasTecnicasBase: 12,
    fatorComplexidade: 1.0,
    valorReferenciaHora: 200,
    fonte: 'enviro-clarity-main',
    codigoOrigem: 'LIC-007',
    demandType: 'Manutenção de licença',
    sphere: 'Estadual / Municipal',
    agencies: ['AMMA', 'SEMAD-GO', 'IBAMA'],
    complexity: 'Baixa',
    professionals: ['Engenheiro Ambiental', 'Biólogo'],
    deliverableType: 'Estudo ambiental',
    precoBase: 4000,
    precoMin: 2500,
    precoMax: 7000,
    custoInterno: 1800,
    margem: 55,
    fluxo: 'pontual',
    requerDiagnostico: true,
    orcamentoDireto: false
  },
  {
    codigo: 'LIC-008',
    nome: 'Plano de Controle Ambiental (PCA)',
    descricao: 'Plano técnico com medidas de controle ambiental, programas ambientais e procedimentos de monitoramento para implantação e operação.',
    categoria: 'Licenciamento Ambiental',
    subcategoria: 'Estudos Técnicos',
    horasTecnicasBase: 40,
    fatorComplexidade: 1.2,
    valorReferenciaHora: 200,
    fonte: 'enviro-clarity-main',
    codigoOrigem: 'LIC-008',
    demandType: 'Projeto / Plano técnico',
    sphere: 'Estadual / Municipal',
    agencies: ['AMMA', 'SEMAD-GO', 'IBAMA'],
    complexity: 'Alta',
    professionals: ['Engenheiro Ambiental', 'Biólogo'],
    deliverableType: 'Plano técnico',
    precoBase: 15000,
    precoMin: 8000,
    precoMax: 30000,
    custoInterno: 6000,
    margem: 60,
    fluxo: 'pontual',
    requerDiagnostico: true,
    orcamentoDireto: false
  },
  {
    codigo: 'LIC-009',
    nome: 'Plano de Recuperação de Área Degradada (PRAD)',
    descricao: 'Plano de recuperação ambiental com técnicas de recuperação, seleção de espécies vegetais e programa de monitoramento.',
    categoria: 'Licenciamento Ambiental',
    subcategoria: 'Estudos Técnicos',
    horasTecnicasBase: 32,
    fatorComplexidade: 1.1,
    valorReferenciaHora: 200,
    fonte: 'enviro-clarity-main',
    codigoOrigem: 'LIC-009',
    demandType: 'Projeto / Plano técnico',
    sphere: 'Estadual / Municipal',
    agencies: ['IBAMA', 'SEMAD-GO', 'AMMA'],
    complexity: 'Média',
    professionals: ['Engenheiro Florestal', 'Biólogo'],
    deliverableType: 'Plano técnico',
    precoBase: 10000,
    precoMin: 6000,
    precoMax: 20000,
    custoInterno: 4000,
    margem: 60,
    fluxo: 'pontual',
    requerDiagnostico: true,
    orcamentoDireto: false
  },
  {
    codigo: 'LIC-010',
    nome: 'Relatório de Atendimento a Condicionantes (RAC)',
    descricao: 'Comprovação do cumprimento das condicionantes ambientais com consolidação de evidências técnicas e registros de monitoramento.',
    categoria: 'Licenciamento Ambiental',
    subcategoria: 'Estudos Técnicos',
    horasTecnicasBase: 12,
    fatorComplexidade: 1.0,
    valorReferenciaHora: 200,
    fonte: 'enviro-clarity-main',
    codigoOrigem: 'LIC-010',
    demandType: 'Operação / Atendimento contínuo',
    sphere: 'Estadual / Municipal',
    agencies: ['AMMA', 'SEMAD-GO', 'IBAMA'],
    complexity: 'Baixa',
    professionals: ['Engenheiro Ambiental', 'Técnico'],
    deliverableType: 'Relatório técnico',
    precoBase: 3500,
    precoMin: 2000,
    precoMax: 6000,
    custoInterno: 1500,
    margem: 57,
    fluxo: 'pontual',
    requerDiagnostico: true,
    orcamentoDireto: false
  },
  {
    codigo: 'LIC-012',
    nome: 'Análise de Viabilidade Ambiental para Novo Empreendimento',
    descricao: 'Avaliação preliminar de viabilidade ambiental incluindo análise locacional, restrições ambientais e compatibilidade com licenciamento.',
    categoria: 'Licenciamento Ambiental',
    subcategoria: 'Estudos Técnicos',
    horasTecnicasBase: 16,
    fatorComplexidade: 1.0,
    valorReferenciaHora: 200,
    fonte: 'enviro-clarity-main',
    codigoOrigem: 'LIC-012',
    demandType: 'Diagnóstico / Estudo',
    sphere: 'Estadual / Municipal',
    agencies: ['AMMA', 'SEMAD-GO', 'Prefeitura'],
    complexity: 'Média',
    professionals: ['Engenheiro Ambiental', 'Geógrafo'],
    deliverableType: 'Estudo ambiental',
    precoBase: 6000,
    precoMin: 3500,
    precoMax: 12000,
    custoInterno: 2500,
    margem: 58,
    fluxo: 'pontual',
    requerDiagnostico: true,
    orcamentoDireto: false
  },
  {
    codigo: 'LIC-013',
    nome: 'Cadastro no CTF IBAMA',
    descricao: 'Cadastro técnico federal de atividades potencialmente poluidoras junto ao IBAMA com enquadramento e registro no CTF/APP.',
    categoria: 'Licenciamento Ambiental',
    subcategoria: 'Regularização e Gestão',
    horasTecnicasBase: 6,
    fatorComplexidade: 1.0,
    valorReferenciaHora: 200,
    fonte: 'enviro-clarity-main',
    codigoOrigem: 'LIC-013',
    demandType: 'Licenciamento',
    sphere: 'Federal',
    agencies: ['IBAMA'],
    complexity: 'Média',
    professionals: ['Engenheiro Ambiental', 'Técnico'],
    deliverableType: 'Certificado / Cadastro',
    precoBase: 2000,
    precoMin: 1000,
    precoMax: 4000,
    custoInterno: 800,
    margem: 60,
    fluxo: 'pontual',
    requerDiagnostico: true,
    orcamentoDireto: false
  },
  {
    codigo: 'LIC-014',
    nome: 'Elaboração e Protocolo de Processos LP, LI e LO',
    descricao: 'Condução técnica da elaboração e protocolo de processos de LP, LI e LO incluindo documentação, estudos e acompanhamento.',
    categoria: 'Licenciamento Ambiental',
    subcategoria: 'Regularização e Gestão',
    horasTecnicasBase: 32,
    fatorComplexidade: 1.1,
    valorReferenciaHora: 200,
    fonte: 'enviro-clarity-main',
    codigoOrigem: 'LIC-014',
    demandType: 'Licenciamento',
    sphere: 'Estadual / Municipal',
    agencies: ['AMMA', 'SEMAD-GO', 'IBAMA'],
    complexity: 'Média',
    professionals: ['Engenheiro Ambiental'],
    deliverableType: 'Licença ambiental',
    precoBase: 8000,
    precoMin: 5000,
    precoMax: 15000,
    custoInterno: 3500,
    margem: 56,
    fluxo: 'pontual',
    requerDiagnostico: true,
    orcamentoDireto: false
  },
  {
    codigo: 'LIC-015',
    nome: 'Renovação de Licenças Ambientais',
    descricao: 'Processo de renovação com análise de condicionantes, documentação e protocolo dentro dos prazos legais.',
    categoria: 'Licenciamento Ambiental',
    subcategoria: 'Regularização e Gestão',
    horasTecnicasBase: 12,
    fatorComplexidade: 1.0,
    valorReferenciaHora: 200,
    fonte: 'enviro-clarity-main',
    codigoOrigem: 'LIC-015',
    demandType: 'Renovação',
    sphere: 'Estadual / Municipal',
    agencies: ['AMMA', 'SEMAD-GO', 'IBAMA'],
    complexity: 'Baixa',
    professionals: ['Engenheiro Ambiental'],
    deliverableType: 'Licença ambiental',
    precoBase: 4000,
    precoMin: 2500,
    precoMax: 7000,
    custoInterno: 1500,
    margem: 62,
    fluxo: 'pontual',
    requerDiagnostico: true,
    orcamentoDireto: false
  },
  {
    codigo: 'LIC-016',
    nome: 'Retificação e Atualização de Licenças',
    descricao: 'Retificação e atualização de licenças ambientais com organização documental e interface com órgão competente.',
    categoria: 'Licenciamento Ambiental',
    subcategoria: 'Regularização e Gestão',
    horasTecnicasBase: 8,
    fatorComplexidade: 1.0,
    valorReferenciaHora: 200,
    fonte: 'enviro-clarity-main',
    codigoOrigem: 'LIC-016',
    demandType: 'Regularização / Adequação',
    sphere: 'Estadual / Municipal',
    agencies: ['SEMAD-GO', 'AMMA', 'IBAMA'],
    complexity: 'Baixa',
    professionals: ['Engenheiro Ambiental'],
    deliverableType: 'Licença ambiental',
    precoBase: 2500,
    precoMin: 1500,
    precoMax: 5000,
    custoInterno: 1000,
    margem: 60,
    fluxo: 'pontual',
    requerDiagnostico: true,
    orcamentoDireto: false
  },
  {
    codigo: 'LIC-017',
    nome: 'Acompanhamento de Processos em Órgãos Ambientais',
    descricao: 'Acompanhamento de processos com abordagem técnica, documental e regulatória.',
    categoria: 'Licenciamento Ambiental',
    subcategoria: 'Regularização e Gestão',
    horasTecnicasBase: 6,
    fatorComplexidade: 1.0,
    valorReferenciaHora: 200,
    fonte: 'enviro-clarity-main',
    codigoOrigem: 'LIC-017',
    demandType: 'Operação / Atendimento contínuo',
    sphere: 'Estadual / Municipal',
    agencies: ['SEMAD-GO', 'AMMA', 'IBAMA'],
    complexity: 'Baixa',
    professionals: ['Técnico', 'Engenheiro Ambiental'],
    deliverableType: 'Relatório técnico',
    precoBase: 2000,
    precoMin: 1200,
    precoMax: 4000,
    custoInterno: 800,
    margem: 60,
    fluxo: 'pontual',
    requerDiagnostico: true,
    orcamentoDireto: false,
    metadata: {
      commercialNotes: 'Pode ser contratado como mensalidade'
    }
  },
  {
    codigo: 'LIC-018',
    nome: 'Atendimento a Diligências Técnicas',
    descricao: 'Atendimento a diligências técnicas com documentação, suporte técnico e interface com o órgão competente.',
    categoria: 'Licenciamento Ambiental',
    subcategoria: 'Regularização e Gestão',
    horasTecnicasBase: 16,
    fatorComplexidade: 1.0,
    valorReferenciaHora: 200,
    fonte: 'enviro-clarity-main',
    codigoOrigem: 'LIC-018',
    demandType: 'Licenciamento',
    sphere: 'Estadual / Municipal',
    agencies: ['SEMAD-GO', 'AMMA', 'IBAMA'],
    complexity: 'Média',
    professionals: ['Engenheiro Ambiental'],
    deliverableType: 'Estudo ambiental',
    precoBase: 5000,
    precoMin: 3000,
    precoMax: 10000,
    custoInterno: 2000,
    margem: 60,
    fluxo: 'pontual',
    requerDiagnostico: true,
    orcamentoDireto: false
  },
  {
    codigo: 'LIC-019',
    nome: 'Controle de Condicionantes Ambientais',
    descricao: 'Controle e cumprimento de condicionantes ambientais com abordagem técnica e regulatória.',
    categoria: 'Licenciamento Ambiental',
    subcategoria: 'Regularização e Gestão',
    horasTecnicasBase: 8,
    fatorComplexidade: 1.0,
    valorReferenciaHora: 200,
    fonte: 'enviro-clarity-main',
    codigoOrigem: 'LIC-019',
    demandType: 'Operação / Atendimento contínuo',
    sphere: 'Estadual / Municipal',
    agencies: ['SEMAD-GO', 'AMMA', 'IBAMA'],
    complexity: 'Baixa',
    professionals: ['Técnico Ambiental'],
    deliverableType: 'Relatório técnico',
    precoBase: 2500,
    precoMin: 1500,
    precoMax: 5000,
    custoInterno: 1000,
    margem: 60,
    fluxo: 'pontual',
    requerDiagnostico: true,
    orcamentoDireto: false
  },
  {
    codigo: 'LIC-020',
    nome: 'Gestão de Prazos e Validade de Licenças',
    descricao: 'Gestão de prazos e validade de licenças com organização documental e alerta de vencimentos.',
    categoria: 'Licenciamento Ambiental',
    subcategoria: 'Regularização e Gestão',
    horasTecnicasBase: 4,
    fatorComplexidade: 1.0,
    valorReferenciaHora: 200,
    fonte: 'enviro-clarity-main',
    codigoOrigem: 'LIC-020',
    demandType: 'Operação / Atendimento contínuo',
    sphere: 'Estadual / Municipal',
    agencies: ['SEMAD-GO', 'AMMA', 'IBAMA'],
    complexity: 'Baixa',
    professionals: ['Administrativo', 'Técnico'],
    deliverableType: 'Licença ambiental',
    precoBase: 1500,
    precoMin: 800,
    precoMax: 3000,
    custoInterno: 600,
    margem: 60,
    fluxo: 'pontual',
    requerDiagnostico: true,
    orcamentoDireto: false
  },

  // ─── RECURSOS HÍDRICOS E OUTORGA ───────────────────────
  {
    codigo: 'OUT-001',
    nome: 'Declaração de Uso de Recursos Hídricos (Dispensa)',
    descricao: 'Estruturação de dados técnicos e administrativos para regularização ou dispensa de outorga de uso de recursos hídricos.',
    categoria: 'Recursos Hídricos e Outorga',
    subcategoria: 'Outorga de Água',
    horasTecnicasBase: 6,
    fatorComplexidade: 1.0,
    valorReferenciaHora: 200,
    fonte: 'enviro-clarity-main',
    codigoOrigem: 'OUT-001',
    demandType: 'Outorga / Regularização hídrica',
    sphere: 'Estadual / Federal',
    agencies: ['SEMAD-GO', 'ANA'],
    complexity: 'Baixa',
    professionals: ['Engenheiro Ambiental'],
    deliverableType: 'Relatório técnico',
    precoBase: 2000,
    precoMin: 1200,
    precoMax: 4000,
    custoInterno: 800,
    margem: 60,
    fluxo: 'pontual',
    requerDiagnostico: true,
    orcamentoDireto: false
  },
  {
    codigo: 'OUT-002',
    nome: 'Outorga — Captação Superficial ou Subterrânea',
    descricao: 'Estruturação técnica e administrativa para obtenção de outorga de captação superficial ou subterrânea.',
    categoria: 'Recursos Hídricos e Outorga',
    subcategoria: 'Outorga de Água',
    horasTecnicasBase: 20,
    fatorComplexidade: 1.0,
    valorReferenciaHora: 200,
    fonte: 'enviro-clarity-main',
    codigoOrigem: 'OUTORGA_CAPTACAO_SUPERFICIAL',
    demandType: 'Outorga / Regularização hídrica',
    sphere: 'Estadual / Federal',
    agencies: ['SEMAD-GO', 'ANA'],
    complexity: 'Média',
    professionals: ['Engenheiro Ambiental', 'Agrônomo', 'Geólogo'],
    deliverableType: 'Portaria de Outorga',
    precoBase: 6000,
    precoMin: 3500,
    precoMax: 12000,
    custoInterno: 2500,
    margem: 58,
    fluxo: 'pontual',
    requerDiagnostico: true,
    orcamentoDireto: false
  },
  {
    codigo: 'OUT-003',
    nome: 'Renovação de Outorga de Uso da Água',
    descricao: 'Renovação de outorga de uso da água com atualização de dados técnicos e administrativos.',
    categoria: 'Recursos Hídricos e Outorga',
    subcategoria: 'Outorga de Água',
    horasTecnicasBase: 10,
    fatorComplexidade: 1.0,
    valorReferenciaHora: 200,
    fonte: 'enviro-clarity-main',
    codigoOrigem: 'OUT-003',
    demandType: 'Renovação',
    sphere: 'Estadual / Federal',
    agencies: ['SEMAD-GO', 'ANA'],
    complexity: 'Baixa',
    professionals: ['Engenheiro Ambiental'],
    deliverableType: 'Portaria de Outorga',
    precoBase: 3000,
    precoMin: 1800,
    precoMax: 6000,
    custoInterno: 1200,
    margem: 60,
    fluxo: 'pontual',
    requerDiagnostico: true,
    orcamentoDireto: false
  },
  {
    codigo: 'OUT-004',
    nome: 'Outorga para Lançamento de Efluentes',
    descricao: 'Obtenção de outorga para lançamento de efluentes tratados em corpos hídricos.',
    categoria: 'Recursos Hídricos e Outorga',
    subcategoria: 'Outorga de Água',
    horasTecnicasBase: 24,
    fatorComplexidade: 1.0,
    valorReferenciaHora: 200,
    fonte: 'enviro-clarity-main',
    codigoOrigem: 'OUT-004',
    demandType: 'Outorga / Regularização hídrica',
    sphere: 'Estadual / Federal',
    agencies: ['SEMAD-GO', 'ANA'],
    complexity: 'Média',
    professionals: ['Engenheiro Ambiental', 'Sanitarista'],
    deliverableType: 'Portaria de Outorga',
    precoBase: 7000,
    precoMin: 4000,
    precoMax: 14000,
    custoInterno: 3000,
    margem: 57,
    fluxo: 'pontual',
    requerDiagnostico: true,
    orcamentoDireto: false
  },
  {
    codigo: 'OUT-005',
    nome: 'Cadastramento CNARH / SIGARH / Veredas',
    descricao: 'Cadastramento em sistemas de gestão de recursos hídricos com abordagem técnica e documental.',
    categoria: 'Recursos Hídricos e Outorga',
    subcategoria: 'Outorga de Água',
    horasTecnicasBase: 4,
    fatorComplexidade: 1.0,
    valorReferenciaHora: 200,
    fonte: 'enviro-clarity-main',
    codigoOrigem: 'CADASTRO_USUARIO_VEREDAS',
    demandType: 'Outorga / Regularização hídrica',
    sphere: 'Estadual / Federal',
    agencies: ['SEMAD-GO', 'ANA'],
    complexity: 'Baixa',
    professionals: ['Técnico', 'Administrativo'],
    deliverableType: 'Relatório técnico',
    precoBase: 1500,
    precoMin: 800,
    precoMax: 3000,
    custoInterno: 600,
    margem: 60,
    fluxo: 'pontual',
    requerDiagnostico: true,
    orcamentoDireto: false
  },
  {
    codigo: 'OUT-006',
    nome: 'Outorga para Irrigação',
    descricao: 'Obtenção de outorga de direito de uso da água para irrigação com dados técnicos e hidrológicos.',
    categoria: 'Recursos Hídricos e Outorga',
    subcategoria: 'Outorga de Água',
    horasTecnicasBase: 40,
    fatorComplexidade: 1.2,
    valorReferenciaHora: 200,
    fonte: 'enviro-clarity-main',
    codigoOrigem: 'OUT-006',
    demandType: 'Outorga / Regularização hídrica',
    sphere: 'Estadual / Federal',
    agencies: ['SEMAD-GO', 'ANA'],
    complexity: 'Alta',
    professionals: ['Engenheiro Ambiental', 'Hidrólogo'],
    deliverableType: 'Portaria de Outorga',
    precoBase: 12000,
    precoMin: 7000,
    precoMax: 25000,
    custoInterno: 5000,
    margem: 58,
    fluxo: 'pontual',
    requerDiagnostico: true,
    orcamentoDireto: false
  },
  {
    codigo: 'OUT-007',
    nome: 'Mapeamento de Captações e Poços Tubulares',
    descricao: 'Mapeamento georreferenciado de captações e poços tubulares para diagnóstico hídrico.',
    categoria: 'Recursos Hídricos e Outorga',
    subcategoria: 'Outorga de Água',
    horasTecnicasBase: 16,
    fatorComplexidade: 1.0,
    valorReferenciaHora: 200,
    fonte: 'enviro-clarity-main',
    codigoOrigem: 'OUT-007',
    demandType: 'Diagnóstico / Estudo',
    sphere: 'Estadual / Federal',
    agencies: ['SEMAD-GO', 'ANA'],
    complexity: 'Média',
    professionals: ['Técnico', 'Analista GIS'],
    deliverableType: 'Plano técnico',
    precoBase: 5000,
    precoMin: 3000,
    precoMax: 10000,
    custoInterno: 2000,
    margem: 60,
    fluxo: 'pontual',
    requerDiagnostico: true,
    orcamentoDireto: false
  },
  {
    codigo: 'OUT-008',
    nome: 'Balanço Hídrico de Propriedade',
    descricao: 'Balanço hídrico da propriedade com avaliação de disponibilidade e demanda de água.',
    categoria: 'Recursos Hídricos e Outorga',
    subcategoria: 'Estudos Hidrológicos',
    horasTecnicasBase: 20,
    fatorComplexidade: 1.0,
    valorReferenciaHora: 200,
    fonte: 'enviro-clarity-main',
    codigoOrigem: 'OUT-008',
    demandType: 'Outorga / Regularização hídrica',
    sphere: 'Estadual / Federal',
    agencies: ['SEMAD-GO', 'ANA'],
    complexity: 'Média',
    professionals: ['Engenheiro Ambiental', 'Hidrólogo'],
    deliverableType: 'Relatório técnico',
    precoBase: 6000,
    precoMin: 3500,
    precoMax: 12000,
    custoInterno: 2500,
    margem: 58,
    fluxo: 'pontual',
    requerDiagnostico: true,
    orcamentoDireto: false
  },
  {
    codigo: 'OUT-009',
    nome: 'Estudo de Demanda Hídrica para Irrigação',
    descricao: 'Estudo de demanda hídrica para dimensionamento de sistemas de irrigação.',
    categoria: 'Recursos Hídricos e Outorga',
    subcategoria: 'Estudos Hidrológicos',
    horasTecnicasBase: 16,
    fatorComplexidade: 1.0,
    valorReferenciaHora: 200,
    fonte: 'enviro-clarity-main',
    codigoOrigem: 'OUT-009',
    demandType: 'Outorga / Regularização hídrica',
    sphere: 'Estadual / Federal',
    agencies: ['SEMAD-GO', 'ANA'],
    complexity: 'Média',
    professionals: ['Engenheiro Ambiental', 'Agrônomo'],
    deliverableType: 'Estudo ambiental',
    precoBase: 5000,
    precoMin: 3000,
    precoMax: 10000,
    custoInterno: 2000,
    margem: 60,
    fluxo: 'pontual',
    requerDiagnostico: true,
    orcamentoDireto: false
  },
  {
    codigo: 'OUT-010',
    nome: 'Dimensionamento de Barramento / Açude',
    descricao: 'Dimensionamento técnico de barramento ou açude para captação e armazenamento de água.',
    categoria: 'Recursos Hídricos e Outorga',
    subcategoria: 'Estudos Hidrológicos',
    horasTecnicasBase: 60,
    fatorComplexidade: 1.3,
    valorReferenciaHora: 200,
    fonte: 'enviro-clarity-main',
    codigoOrigem: 'OUT-010',
    demandType: 'Outorga / Regularização hídrica',
    sphere: 'Estadual / Federal',
    agencies: ['SEMAD-GO', 'ANA'],
    complexity: 'Alta',
    professionals: ['Engenheiro Civil', 'Ambiental'],
    deliverableType: 'Projeto executivo',
    precoBase: 20000,
    precoMin: 12000,
    precoMax: 40000,
    custoInterno: 8000,
    margem: 60,
    fluxo: 'pontual',
    requerDiagnostico: true,
    orcamentoDireto: false
  },
  {
    codigo: 'OUT-011',
    nome: 'Cálculo de Vazão Média e Q7,10',
    descricao: 'Cálculo hidrológico de vazão média e Q7,10 para subsidiar processos de outorga.',
    categoria: 'Recursos Hídricos e Outorga',
    subcategoria: 'Estudos Hidrológicos',
    horasTecnicasBase: 12,
    fatorComplexidade: 1.0,
    valorReferenciaHora: 200,
    fonte: 'enviro-clarity-main',
    codigoOrigem: 'OUT-011',
    demandType: 'Outorga / Regularização hídrica',
    sphere: 'Estadual / Federal',
    agencies: ['SEMAD-GO', 'ANA'],
    complexity: 'Média',
    professionals: ['Engenheiro Ambiental', 'Hidrólogo'],
    deliverableType: 'Relatório técnico',
    precoBase: 4000,
    precoMin: 2500,
    precoMax: 8000,
    custoInterno: 1800,
    margem: 55,
    fluxo: 'pontual',
    requerDiagnostico: true,
    orcamentoDireto: false
  },
  {
    codigo: 'OUT-012',
    nome: 'Avaliação de Interferência entre Poços',
    descricao: 'Avaliação técnica de interferência entre poços com suporte documental e interface com órgão competente.',
    categoria: 'Recursos Hídricos e Outorga',
    subcategoria: 'Estudos Hidrológicos',
    horasTecnicasBase: 16,
    fatorComplexidade: 1.0,
    valorReferenciaHora: 200,
    fonte: 'enviro-clarity-main',
    codigoOrigem: 'OUT-012',
    demandType: 'Diagnóstico / Estudo',
    sphere: 'Estadual / Federal',
    agencies: ['SEMAD-GO', 'ANA'],
    complexity: 'Média',
    professionals: ['Hidrólogo', 'Engenheiro Ambiental'],
    deliverableType: 'Relatório técnico',
    precoBase: 5000,
    precoMin: 3000,
    precoMax: 10000,
    custoInterno: 2000,
    margem: 60,
    fluxo: 'pontual',
    requerDiagnostico: true,
    orcamentoDireto: false
  },
  {
    codigo: 'OUT-014',
    nome: 'Laudo de Teste de Vazão de Poços',
    descricao: 'Teste de vazão de poços com estruturação de dados técnicos para regularização hídrica.',
    categoria: 'Recursos Hídricos e Outorga',
    subcategoria: 'Estudos Hidrológicos',
    horasTecnicasBase: 12,
    fatorComplexidade: 1.0,
    valorReferenciaHora: 200,
    fonte: 'enviro-clarity-main',
    codigoOrigem: 'OUT-014',
    demandType: 'Diagnóstico / Estudo',
    sphere: 'Estadual / Federal',
    agencies: ['SEMAD-GO', 'ANA'],
    complexity: 'Média',
    professionals: ['Técnico', 'Engenheiro Ambiental'],
    deliverableType: 'Laudo técnico',
    precoBase: 3500,
    precoMin: 2000,
    precoMax: 7000,
    custoInterno: 1500,
    margem: 57,
    fluxo: 'pontual',
    requerDiagnostico: true,
    orcamentoDireto: false
  },
  {
    codigo: 'OUT-016',
    nome: 'Regularização de captação superficial para umectação',
    descricao: 'Regularização de captação superficial temporária para abastecimento de caminhão-pipa em frentes de umectação e controle de poeira.',
    categoria: 'Recursos Hídricos e Outorga',
    subcategoria: 'Outorga de Água',
    horasTecnicasBase: 8,
    fatorComplexidade: 1.0,
    valorReferenciaHora: 200,
    fonte: 'enviro-clarity-main',
    codigoOrigem: 'SRV-HID-OUT-UMECT-001',
    demandType: 'Outorga / Regularização hídrica',
    sphere: 'Estadual / Federal',
    agencies: ['SEMAD-GO', 'ANA'],
    complexity: 'Baixa',
    professionals: ['Engenheiro Ambiental', 'Analista GIS'],
    deliverableType: 'Diagnóstico técnico + protocolo hídrico',
    precoBase: 3200,
    precoMin: 2000,
    precoMax: 3500,
    custoInterno: 1200,
    margem: 62,
    fluxo: 'pontual',
    requerDiagnostico: true,
    orcamentoDireto: false,
    metadata: {
      whenToApply: 'Terraplanagem, loteamentos e frentes temporárias com uso de água superficial para umectação.',
      triggers: 'Captação superficial com caminhão-pipa; ponto fora da propriedade; necessidade de validar acesso, titularidade e enquadramento hídrico.',
      referenceTimeline: '7–15 dias úteis',
      steps: 'Validação locacional → enquadramento hídrico → estruturação documental → protocolo inicial'
    }
  },

  // ─── ESTUDOS AMBIENTAIS E PASSIVO ──────────────────────
  {
    codigo: 'EST-001',
    nome: 'Diagnóstico de Passivo Ambiental',
    descricao: 'Base técnica para diagnóstico de passivo ambiental subsidiando decisão, licenciamento e regularização.',
    categoria: 'Estudos Ambientais e Passivo',
    subcategoria: 'Diagnóstico e Investigação',
    horasTecnicasBase: 40,
    fatorComplexidade: 1.2,
    valorReferenciaHora: 250,
    fonte: 'enviro-clarity-main',
    codigoOrigem: 'EST-001',
    demandType: 'Regularização / Adequação',
    sphere: 'Estadual / Federal',
    agencies: ['Órgão licenciador'],
    complexity: 'Alta',
    professionals: ['Engenheiro Ambiental', 'Geólogo', 'Biólogo'],
    deliverableType: 'Relatório técnico',
    precoBase: 15000,
    precoMin: 8000,
    precoMax: 30000,
    custoInterno: 6000,
    margem: 60,
    fluxo: 'pontual',
    requerDiagnostico: true,
    orcamentoDireto: false
  },
  {
    codigo: 'EST-002',
    nome: 'Avaliação Preliminar Ambiental (APA — NBR 15.515-1)',
    descricao: 'Avaliação preliminar conforme ABNT NBR 15.515-1 com documentação e interface com órgão competente.',
    categoria: 'Estudos Ambientais e Passivo',
    subcategoria: 'Diagnóstico e Investigação',
    horasTecnicasBase: 24,
    fatorComplexidade: 1.0,
    valorReferenciaHora: 200,
    fonte: 'enviro-clarity-main',
    codigoOrigem: 'EST-002',
    demandType: 'Diagnóstico / Estudo',
    sphere: 'Estadual / Federal',
    agencies: ['Órgão licenciador'],
    complexity: 'Média',
    professionals: ['Engenheiro Ambiental', 'Biólogo'],
    deliverableType: 'Estudo ambiental',
    precoBase: 8000,
    precoMin: 5000,
    precoMax: 15000,
    custoInterno: 3500,
    margem: 56,
    fluxo: 'pontual',
    requerDiagnostico: true,
    orcamentoDireto: false
  },
  {
    codigo: 'EST-003',
    nome: 'Investigação Confirmatória Ambiental (ICA — NBR 15.515-2)',
    descricao: 'Investigação confirmatória conforme NBR 15.515-2 para subsidiar decisão e regularização.',
    categoria: 'Estudos Ambientais e Passivo',
    subcategoria: 'Diagnóstico e Investigação',
    horasTecnicasBase: 60,
    fatorComplexidade: 1.2,
    valorReferenciaHora: 200,
    fonte: 'enviro-clarity-main',
    codigoOrigem: 'EST-003',
    demandType: 'Diagnóstico / Estudo',
    sphere: 'Estadual / Federal',
    agencies: ['Órgão licenciador'],
    complexity: 'Alta',
    professionals: ['Engenheiro Ambiental', 'Geólogo', 'Biólogo'],
    deliverableType: 'Estudo ambiental',
    precoBase: 20000,
    precoMin: 12000,
    precoMax: 40000,
    custoInterno: 8000,
    margem: 60,
    fluxo: 'pontual',
    requerDiagnostico: true,
    orcamentoDireto: false
  },
  {
    codigo: 'EST-004',
    nome: 'Investigação Detalhada Ambiental (IDA — NBR 15.515-3)',
    descricao: 'Investigação detalhada conforme NBR 15.515-3 para caracterização completa de contaminação.',
    categoria: 'Estudos Ambientais e Passivo',
    subcategoria: 'Diagnóstico e Investigação',
    horasTecnicasBase: 80,
    fatorComplexidade: 1.2,
    valorReferenciaHora: 200,
    fonte: 'enviro-clarity-main',
    codigoOrigem: 'EST-004',
    demandType: 'Diagnóstico / Estudo',
    sphere: 'Estadual / Federal',
    agencies: ['Órgão licenciador'],
    complexity: 'Alta',
    professionals: ['Engenheiro Ambiental', 'Geólogo', 'Biólogo'],
    deliverableType: 'Estudo ambiental',
    precoBase: 30000,
    precoMin: 18000,
    precoMax: 60000,
    custoInterno: 12000,
    margem: 60,
    fluxo: 'pontual',
    requerDiagnostico: true,
    orcamentoDireto: false
  },
  {
    codigo: 'EST-005',
    nome: 'Plano de Investigação Ambiental (PIA)',
    descricao: 'Plano de investigação ambiental para subsídio de decisão e regularização.',
    categoria: 'Estudos Ambientais e Passivo',
    subcategoria: 'Diagnóstico e Investigação',
    horasTecnicasBase: 32,
    fatorComplexidade: 1.1,
    valorReferenciaHora: 200,
    fonte: 'enviro-clarity-main',
    codigoOrigem: 'EST-005',
    demandType: 'Diagnóstico / Estudo',
    sphere: 'Estadual / Federal',
    agencies: ['Órgão licenciador'],
    complexity: 'Alta',
    professionals: ['Engenheiro Ambiental', 'Geólogo', 'Químico'],
    deliverableType: 'Plano técnico',
    precoBase: 12000,
    precoMin: 7000,
    precoMax: 25000,
    custoInterno: 5000,
    margem: 58,
    fluxo: 'pontual',
    requerDiagnostico: true,
    orcamentoDireto: false
  },
  {
    codigo: 'EST-006',
    nome: 'Plano de Intervenção Ambiental',
    descricao: 'Plano de intervenção com medidas, programas e controles para o empreendimento.',
    categoria: 'Estudos Ambientais e Passivo',
    subcategoria: 'Remediação e Monitoramento',
    horasTecnicasBase: 40,
    fatorComplexidade: 1.1,
    valorReferenciaHora: 200,
    fonte: 'enviro-clarity-main',
    codigoOrigem: 'EST-006',
    demandType: 'Projeto / Plano técnico',
    sphere: 'Estadual / Federal',
    agencies: ['Órgão licenciador'],
    complexity: 'Alta',
    professionals: ['Engenheiro Ambiental'],
    deliverableType: 'Plano técnico',
    precoBase: 15000,
    precoMin: 8000,
    precoMax: 30000,
    custoInterno: 6000,
    margem: 60,
    fluxo: 'pontual',
    requerDiagnostico: true,
    orcamentoDireto: false
  },
  {
    codigo: 'EST-007',
    nome: 'Plano de Remediação Ambiental (PRA)',
    descricao: 'Plano de remediação com escopo técnico orientando medidas e controles ambientais.',
    categoria: 'Estudos Ambientais e Passivo',
    subcategoria: 'Remediação e Monitoramento',
    horasTecnicasBase: 60,
    fatorComplexidade: 1.1,
    valorReferenciaHora: 200,
    fonte: 'enviro-clarity-main',
    codigoOrigem: 'EST-007',
    demandType: 'Projeto / Plano técnico',
    sphere: 'Estadual / Federal',
    agencies: ['Órgão licenciador'],
    complexity: 'Alta',
    professionals: ['Engenheiro Ambiental', 'Químico'],
    deliverableType: 'Plano técnico',
    precoBase: 20000,
    precoMin: 12000,
    precoMax: 40000,
    custoInterno: 8000,
    margem: 60,
    fluxo: 'pontual',
    requerDiagnostico: true,
    orcamentoDireto: false
  },
  {
    codigo: 'EST-008',
    nome: 'Monitoramento Pós-Remediação',
    descricao: 'Monitoramento pós-remediação para verificar conformidade e gerar evidências técnicas.',
    categoria: 'Estudos Ambientais e Passivo',
    subcategoria: 'Remediação e Monitoramento',
    horasTecnicasBase: 16,
    fatorComplexidade: 1.0,
    valorReferenciaHora: 200,
    fonte: 'enviro-clarity-main',
    codigoOrigem: 'EST-008',
    demandType: 'Operação / Atendimento contínuo',
    sphere: 'Estadual / Federal',
    agencies: ['Órgão licenciador'],
    complexity: 'Média',
    professionals: ['Engenheiro Ambiental', 'Técnico'],
    deliverableType: 'Relatório de monitoramento',
    precoBase: 5000,
    precoMin: 3000,
    precoMax: 10000,
    custoInterno: 2000,
    margem: 60,
    fluxo: 'pontual',
    requerDiagnostico: true,
    orcamentoDireto: false
  },
  {
    codigo: 'EST-009',
    nome: 'Relatório de Encerramento de Passivo Ambiental',
    descricao: 'Relatório de encerramento de passivo com abordagem técnica, documental e regulatória.',
    categoria: 'Estudos Ambientais e Passivo',
    subcategoria: 'Remediação e Monitoramento',
    horasTecnicasBase: 32,
    fatorComplexidade: 1.1,
    valorReferenciaHora: 200,
    fonte: 'enviro-clarity-main',
    codigoOrigem: 'EST-009',
    demandType: 'Regularização / Adequação',
    sphere: 'Estadual / Federal',
    agencies: ['Órgão licenciador'],
    complexity: 'Alta',
    professionals: ['Engenheiro Ambiental'],
    deliverableType: 'Relatório técnico',
    precoBase: 10000,
    precoMin: 6000,
    precoMax: 20000,
    custoInterno: 4000,
    margem: 60,
    fluxo: 'pontual',
    requerDiagnostico: true,
    orcamentoDireto: false
  },
  {
    codigo: 'EST-010',
    nome: 'Acompanhamento Técnico de Obras de Remediação',
    descricao: 'Acompanhamento técnico orientando medidas, programas e controles.',
    categoria: 'Estudos Ambientais e Passivo',
    subcategoria: 'Remediação e Monitoramento',
    horasTecnicasBase: 20,
    fatorComplexidade: 1.0,
    valorReferenciaHora: 200,
    fonte: 'enviro-clarity-main',
    codigoOrigem: 'EST-010',
    demandType: 'Operação / Atendimento contínuo',
    sphere: 'Estadual / Federal',
    agencies: ['Órgão licenciador'],
    complexity: 'Média',
    professionals: ['Engenheiro Ambiental', 'Técnico'],
    deliverableType: 'Estudo ambiental',
    precoBase: 6000,
    precoMin: 3500,
    precoMax: 12000,
    custoInterno: 2500,
    margem: 58,
    fluxo: 'pontual',
    requerDiagnostico: true,
    orcamentoDireto: false
  },

  // ─── GESTÃO E CONSULTORIA AMBIENTAL ────────────────────
  {
    codigo: 'GES-001',
    nome: 'Consultoria Ambiental Estratégica',
    descricao: 'Consultoria ambiental estratégica com abordagem técnica, documental e regulatória.',
    categoria: 'Gestão e Consultoria Ambiental',
    subcategoria: 'Consultoria Técnica',
    horasTecnicasBase: 16,
    fatorComplexidade: 1.1,
    valorReferenciaHora: 250,
    fonte: 'enviro-clarity-main',
    codigoOrigem: 'GES-001',
    demandType: 'Serviço técnico ambiental',
    sphere: 'Estadual / Municipal',
    agencies: ['Órgão licenciador', 'Prefeitura'],
    complexity: 'Média',
    professionals: ['Engenheiro Ambiental', 'Gestor Ambiental'],
    deliverableType: 'Estudo ambiental',
    precoBase: 6000,
    precoMin: 3500,
    precoMax: 12000,
    custoInterno: 2500,
    margem: 58,
    fluxo: 'pontual',
    requerDiagnostico: true,
    orcamentoDireto: false
  },
  {
    codigo: 'GES-002',
    nome: 'Parecer Técnico Ambiental',
    descricao: 'Parecer técnico ambiental subsidiando decisão, licenciamento e regularização.',
    categoria: 'Gestão e Consultoria Ambiental',
    subcategoria: 'Consultoria Técnica',
    horasTecnicasBase: 8,
    fatorComplexidade: 1.0,
    valorReferenciaHora: 200,
    fonte: 'enviro-clarity-main',
    codigoOrigem: 'GES-002',
    demandType: 'Diagnóstico / Estudo',
    sphere: 'Estadual / Municipal',
    agencies: ['Órgão licenciador', 'Prefeitura'],
    complexity: 'Baixa',
    professionals: ['Engenheiro Ambiental', 'Biólogo'],
    deliverableType: 'Parecer técnico',
    precoBase: 3000,
    precoMin: 1800,
    precoMax: 6000,
    custoInterno: 1200,
    margem: 60,
    fluxo: 'pontual',
    requerDiagnostico: true,
    orcamentoDireto: false
  }
]

export async function seedBaseInterface(prisma: PrismaClient) {
  console.log('🌱 Iniciando seed incremental do catálogo base INTERFACE...')

  let countCreated = 0
  let countUpdated = 0

  for (const servico of SERVICOS_BASE) {
    const data = {
      nome: servico.nome,
      descricao: servico.descricao,
      categoria: servico.categoria,
      subcategoria: servico.subcategoria,
      horasTecnicasBase: servico.horasTecnicasBase,
      fatorComplexidade: servico.fatorComplexidade,
      valorReferenciaHora: servico.valorReferenciaHora,
      obrigacaoBaseCodigo: servico.obrigacaoBaseCodigo,
      precoBase: servico.precoBase,
      precoMinimo: servico.precoMin,
      precoMaximo: servico.precoMax,
      custoInternoEstimado: servico.custoInterno,
      margemLucroAlvo: servico.margem,
      recorrente: servico.fluxo === 'continuo',
      mesesRecorrencia: servico.fluxo === 'continuo' ? 12 : null,
      metadata: servico.metadata || {},
      ativo: true,
    }

    const existing = await prisma.servicoCatalogo.findUnique({
      where: { codigo: servico.codigo }
    })

    if (existing) {
      // Atualiza apenas se for da mesma fonte ou se campos estiverem vazios
      await prisma.servicoCatalogo.update({
        where: { codigo: servico.codigo },
        data: {
          // Preservar nome e descrição se já existirem, ou atualizar conforme regra comercial
          ...data,
          metadata: {
            ...(existing.metadata as any || {}),
            ...(servico.metadata || {}),
            codigoOrigemLegacy: servico.codigoOrigem,
            fonteMigracao: 'Onda 2.6.1'
          }
        }
      })
      countUpdated++
    } else {
      await prisma.servicoCatalogo.create({
        data: {
          codigo: servico.codigo,
          ...data,
          metadata: {
            ...(servico.metadata || {}),
            codigoOrigemLegacy: servico.codigoOrigem,
            fonteMigracao: 'Onda 2.6.1'
          }
        }
      })
      countCreated++
    }
  }

  console.log(`✅ Seed base finalizado: ${countCreated} criados, ${countUpdated} atualizados.`)
}
